# Generated by Django 5.1.4 on 2024-12-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_proyecto', models.DateField()),
                ('fecha_create', models.DateTimeField(auto_now_add=True)),
                ('fecha_modification', models.DateTimeField(auto_now=True)),
                ('descripcion', models.TextField()),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='projects/')),
            ],
        ),
    ]
