# Generated by Django 5.1.4 on 2025-09-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto', 'Monto fijo')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimo_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usos_maximos', models.PositiveIntegerField(blank=True, null=True)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
