# Generated by Django 5.1.4 on 2025-03-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
