# Generated by Django 5.1.4 on 2024-12-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
