# Generated by Django 5.1.4 on 2024-12-22 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoHilattis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresa',
            new_name='infoHilattis',
        ),
    ]
