# Generated by Django 5.1.4 on 2025-01-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variante',
            fields=[
                ('id_variante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('img1', models.ImageField(upload_to='variantes/')),
                ('img2', models.ImageField(upload_to='variantes/')),
                ('img3', models.ImageField(upload_to='variantes/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
