# Generated by Django 5.1.4 on 2025-01-06 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_id_variante'),
        ('variants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='productos.producto'),
            preserve_default=False,
        ),
    ]
