# Generated by Django 5.1.4 on 2025-01-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0002_variante_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
