# Generated by Django 5.1.4 on 2025-01-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0003_variante_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variante',
            name='producto',
        ),
    ]
