# Generated by Django 5.1.4 on 2025-01-18 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_producto_variantes_alter_producto_precio'),
        ('variants', '0004_remove_variante_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='variante',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='productos.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variante',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='variantes/'),
        ),
        migrations.AlterField(
            model_name='variante',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='variantes/'),
        ),
        migrations.AlterField(
            model_name='variante',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='variantes/'),
        ),
        migrations.AlterField(
            model_name='variante',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
