# Generated by Django 5.1.4 on 2025-01-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0005_variante_producto_alter_variante_img1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variante',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
