# Generated by Django 5.1.4 on 2024-12-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_id_alter_usuario_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
