# Generated by Django 5.1.4 on 2025-01-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='permiso',
            field=models.CharField(choices=[('admin', 'Admin'), ('default', 'Default')], default='default', max_length=10),
        ),
    ]
