# Generated by Django 5.1.4 on 2025-03-03 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_usuario_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'El DNI debe contener exactamente 8 dígitos numéricos.')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator('^(\\+51)?\\d{9}$', 'El número de teléfono debe ser un celular (9 dígitos) o incluir el prefijo +51 (11 dígitos).')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'El nombre de usuario solo puede contener letras, números y los caracteres @/./+/-/_')]),
        ),
    ]
