# Generated by Django 5.1.4 on 2025-06-22 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('ingrediente', models.TextField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pack', models.BooleanField(default=False)),
                ('img1', models.ImageField(default='productos/default.jpg', upload_to='productos/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('modo_uso', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='categoria.categoria')),
            ],
        ),
    ]
