# Generated by Django 5.1.4 on 2025-01-05 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('variants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estatus',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado')], default='AGOTADO', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='variants.variante'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_default',
            field=models.ImageField(null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='img1',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='is_variable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
