# Generated by Django 5.1.4 on 2025-01-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_id_variante'),
        ('variants', '0004_remove_variante_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='variantes',
            field=models.ManyToManyField(blank=True, related_name='productos', to='variants.variante'),
        ),
    ]
