# Generated by Django 5.1.4 on 2025-03-10 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_categoria_alter_producto_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='visible',
        ),
    ]
