# Generated by Django 5.1.4 on 2025-01-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_variantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='variantes',
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
