# Generated by Django 5.1.4 on 2025-03-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pack',
            field=models.BooleanField(default=False),
        ),
    ]
