# Generated by Django 5.1.4 on 2025-03-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_producto_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
