# Generated by Django 5.1.4 on 2025-01-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_default',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
