# Generated by Django 5.1.4 on 2025-03-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_producto_img1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img1',
            field=models.ImageField(default='productos/default.jpg', upload_to='productos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
