# Generated by Django 5.1.4 on 2025-08-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='dni',
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_documento',
            field=models.CharField(default='000000000000', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de Extranjería'), ('PAS', 'Pasaporte')], default='DNI', max_length=3),
        ),
    ]
