# Generated by Django 5.1.4 on 2025-09-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_email_verified_otp_cliente_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email_verified',
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
