# Generated by Django 5.1.4 on 2025-06-22 04:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('direccion_legal', models.CharField(max_length=255)),
                ('ruc', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El RUC debe contener exactamente 11 dígitos numéricos.')])),
                ('razon_social', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator('Ingrese un correo electrónico válido.')])),
                ('celular', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^(\\+51)?\\d{9}$', 'El número de celular debe contener 9 dígitos o incluir el prefijo +51.')])),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
                ('descripcion', models.TextField()),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('valores', models.TextField()),
                ('facebook', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator('Ingrese una URL válida.')])),
                ('tiktok', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator('Ingrese una URL válida.')])),
                ('instagram', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator('Ingrese una URL válida.')])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
