# Generated by Django 5.1.4 on 2025-03-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0005_producto_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img1', models.ImageField(upload_to='packs/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='packs/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='packs/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='packs/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('productos', models.ManyToManyField(related_name='packs', to='productos.producto')),
            ],
        ),
    ]
