# Generated by Django 5.1.4 on 2025-07-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='img1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='img2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='img3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pack',
            name='img4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
