# Generated by Django 5.1.4 on 2025-08-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pack', '0002_alter_pack_img1_alter_pack_img2_alter_pack_img3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
